### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by lm2a** [hendisantika/facebook-security5#2]
Wonderful example!. It looks like Craig Walls's example. At the beginning I had some issues, but then it worked fine. Would be interesting to find a way to debug in Eclipse the exchanging messages (perhaps some plugin can help). Spring security does everything under the cover and my app was dying silently. But finally I was able to debug, putting breakpoints right inside Spring Security classes.

**Comment by hendisantika** [comment]
Yes, this repo is forked from Craig Walls. But still doesn't work. Need to modify & bug fix the issues.

**Comment by lm2a** [comment]
It would be wonderful if it finally works, because it's a minimalist, easy-to-understand example. I will try to fix it, if I succeed, I'll post the fix.

**Comment by hendisantika** [comment]
Yes, please send PR.

**Comment by lm2a** [comment]
Hi, hendisantika, finally example works. In my case it was a mistake with the client_secret. AKAIK the main problems are a  lack of error messages and of a way to debug Spring Security classes.

**Comment by hendisantika** [comment]
Can You send PR that work for this repo also @lm2a ?
